%macro ip1(x);
  %do i=1 %to 5;
    %do j=1 %to 15;
    data blk;
      z=ranuni(0);
      if 0<z<0.3333 then blk=4;
        else if z>0.6666 then blk=12;
        else blk=8;
    do j=1 to blk;
      x=ranuni(0);
      output;
    end;
    proc sort;
      by x;
    data a1;
      set blk;
        if _n_<=blk/2 then order='Intervention';
        else order='Non-intervention';
    proc sort data=a1;
      by j;
    data a1(rename=(blk=blk_size));
      set a1(drop=j x z);
    proc print data=a1;
      title "Site=&i., Block=&j.";
    %end;
  %end;
%mend ip1;
%ip1(1);
run;
